### DISCUSSION TITLE
Password file authentication does not work using ingress https

### DISCUSSION THREAD

**Discussion by andreyolv** [trinodb/trino#18785] [Q&A]
I follow this [doc](https://trino.io/docs/current/security/tls.html#use-a-load-balancer-to-terminate-tls-https)

I created a user 'admin' with password 'teste', but I can login only in UI. By cli and dbeaver does not work.

I'm trying run Trino on Kubernetes using official helm chart with values:
```
    server:
      config:
        authenticationType: "PASSWORD"
      workerExtraConfig: |-
        internal-communication.shared-secret=test
      coordinatorExtraConfig: |-
        internal-communication.shared-secret=test
        http-server.process-forwarded=true
    auth: 
      passwordAuth: |- 
        admin:$2y$10$k7ISe/n5TicAp4h1UtFU4u.bcCcEOpmCo/1Uuo/xIoAmTsywmRO2S
    accessControl:
      type: configmap
      refreshPeriod: 60s
      rules:
        rules.json: |-
          {
            "catalogs": [
              {
                "user": "admin",
                "allow": "all"
              }
            ],
            "schemas": [
              {
                "user": "admin",
                "owner": true
              }
            ],
            "tables": [
              {
                "user": "admin",
                "privileges": ["SELECT", "INSERT", "DELETE", "UPDATE", "OWNERSHIP"]
              }
            ]
          }

```

My ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trino
  namespace: trino
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - 'XXXXXXXXXXXXX'
    secretName: XXXXXXXXXXXXXX
  rules:
  - host: trino.xxxx
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service: 
            name: trino
            port:
              number: 8080
```

**UI access**
When I access UI on my host 'trino.xxxx' and try login using user 'admin' and password 'teste' the login is OK. If I try a user that does not exist, the login page is reload and remains in same login page.

**cli access**
By trino cli, does not work. Example, the command:
```
./trino --server https://trino.xxx --user=admin --password
```
Apparently it logs in but nothing runs. All return this error:
Error running command: java.net.SocketTimeoutException: Connect timed out

Also, If I try a user and password that does not exist, the same thing happns.

**dbeaver access**
exactly the same as cli access error, trying with a user that exists or not, gives this error in any query:
java.net.SocketTimeoutException: Read timed out

Does anyone have an idea what the problem is?

**Comment by andreyolv** [comment]
But if I download the cli inside the trino container, then I can access the ingress url server using cli

**Reply by luhea** [reply]
hello，if you config mul auth , such as ldap and password .my solution is config multiple auth in Helm's coordinatorExtraConfig. for example: http-server.authentication.type=PASSWORD,password-authenticator.config-files=/opt/trino-auth/ldap.properties,/opt/trino-auth/password.properties. this way defect is you should config local passworld auth

**Comment by Rattapon-Insa** [comment]
I face the same problem. I tried a similar configuration but the error I got from DBeaver is 
`SQL Error: Error executing query: javax.net.ssl.SSLException: Unsupported or unrecognized SSL message`

Here is my configuration

```
    server:
      config:
        authenticationType: "PASSWORD"
      workerExtraConfig: |-
        internal-communication.shared-secret=test
      coordinatorExtraConfig: |-
        internal-communication.shared-secret=test
        http-server.process-forwarded=true
    auth: 
      passwordAuth: |- 
        admin:$2y$08$FgKZlhSaI55KyWC2eBotZeR4uN7pfOk4cOQiVdhUmV/Ct3DzWRvr6
```
  

my ingress:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trino-ingress
  namespace: trino
spec:
  ingressClassName: kong
  tls:
    - secretName: XXXXX
        - XXXXXXXXXX
  rules:
    - host: xxxxxxxx
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: trino-cluster
                port:
                  number: 8080
```

I'm not sure if it will need to configure TLS communication inside trino cluster or not.
