### DISCUSSION TITLE
Login cli only works inside container using ingress https

### DISCUSSION THREAD

**Discussion by andreyolv** [trinodb/trino#18912] [Q&A]
I can only login in trino by cli inside container. 
In my machine is possible to access web page ui, but by cli doesn't work even with ingress enabled and working for UI. Gives this erros:
Error running command: java.net.SocketTimeoutException: Connect timed out

I'm trying run Trino on Kubernetes using official helm chart with values:
```
    server:
      config:
        authenticationType: "PASSWORD"
      workerExtraConfig: |-
        internal-communication.shared-secret=test
      coordinatorExtraConfig: |-
        internal-communication.shared-secret=test
        http-server.process-forwarded=true
    auth: 
      passwordAuth: |- 
        admin:$2y$10$k7ISe/n5TicAp4h1UtFU4u.bcCcEOpmCo/1Uuo/xIoAmTsywmRO2S
    accessControl:
      type: configmap
      refreshPeriod: 60s
      rules:
        rules.json: |-
          {
            "catalogs": [
              {
                "user": "admin",
                "allow": "all"
              }
            ],
            "schemas": [
              {
                "user": "admin",
                "owner": true
              }
            ],
            "tables": [
              {
                "user": "admin",
                "privileges": ["SELECT", "INSERT", "DELETE", "UPDATE", "OWNERSHIP"]
              }
            ]
          }

```

My ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trino
  namespace: trino
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - 'XXXXXXXXXXXXX'
    secretName: XXXXXXXXXXXXXX
  rules:
  - host: trino.xxxx
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service: 
            name: trino
            port:
              number: 8080
```
