### DISCUSSION TITLE
UncheckedIOException: Failed to bind to /0.0.0.0:8443 when enabling HTTPS

### DISCUSSION THREAD

**Discussion by suisenkotoba** [trinodb/trino#19377] [Q&A]
I tried to enable HTTPS in order to enforce password authentication. Trino is deployed on GKE with helm, This is my `values.yaml`:
```yaml
server:
  workers: 2
  autoscaling:
    enabled: false
    maxReplicas: 4
    targetCPUUtilizationPercentage: 70
  config:
    https:
      enabled: true
      port: 8443
      keystore:
        path: "/usr/local/certs/trino.pem"
    query:
      maxMemory: "96GB"
    authenticationType: "PASSWORD"
  log:
    trino:
      level: DEBUG
  workerExtraConfig: |-
    spill-enabled=true
    spiller-spill-path=/tmp/spill
    spill-compression-enabled=true
    spill-encryption-enabled=true

secretMounts:
  - name: keystore-volume
    secretName: trino-keystore
    path: "/usr/local/certs"

service:
  port: 8443
  type: LoadBalancer
  loadBalancerIP: x.x.x.x
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
    networking.gke.io/internal-load-balancer-allow-global-access: "true"

coordinator: {...}
worker: {...}

accessControl:
  type: "configmap"
  refreshPeriod: "60s"
  rules: {...}

additionalConfigProperties:
  - internal-communication.shared-secret=<secret>

auth:
  passwordAuth:<pwd-auth>

additionalCatalogs: {...}
```
The coordinator pod got error: `Unable to create injector, see the following errors` and after few lines I found this: `... Caused by: UncheckedIOException: Failed to bind to /0.0.0.0:8443 ... Caused by: BindException: Address already in use`. Even after I change the port, this kind of error still persisted. I already followed [the official doc](https://trino.io/docs/current/security/tls.html#secure-trino-directly) to enable https, so I have no idea what is wrong with my configuration.
