### DISCUSSION TITLE
Ingest data from Azure Blob Storage without a Hive metastore

### DISCUSSION THREAD

**Discussion by delsehi** [trinodb/trino#20329] [Q&A]
I'm trying to setup Trino with Nessie for creating a data lakehouse with Iceberg tables. I want to ingest data (csv, json, etc) with Trino and load the Iceberg tables (ELT with Trino). 

I've played around with a Docker-compose file: 

```yaml
version: '3.9'

services:
  nessie:
   image: "ghcr.io/projectnessie/nessie"
   ports:
     - 19120:19120
  trino:
    image: trinodb/trino
    volumes:
      - ./trino/nessie.properties:/etc/trino/catalog/nessie.properties:ro
    ports:
      - 8080:8080
```
And I mount a volume with properties: 
```
connector.name=iceberg
iceberg.catalog.type=nessie 
iceberg.nessie-catalog.uri=http://nessie:19120/api/v1
iceberg.nessie-catalog.default-warehouse-dir=/tmp

hive.azure.wasb-storage-account=<The name of my storage account>
hive.azure.wasb-access-key=<My secret key>
```

I cannot figure out how to query a file though and add it. 

I've tried creating schemas like 
```sql
CREATE SCHEMA nessie.mytest WITH ( location = 'wasb://containerName@mystorageaccount.blob.windows.net/somepath');
CREATE TABLE nessie.mytest.testing (name varchar);
```

But I realize this might not work since I'm using Nessie. 
I want to avoid setting up a Hive metastore for the only sake of accessing the data before loading it into Iceberg tables + Nessie. 
Is there any way of doing that or am I really thinking of Trino in the wrong way?

**Comment by delsehi** [comment]
Experimented again.

**docker-compose.yml**
```yaml
version: '3.9'

services:
  nessie:
   image: "ghcr.io/projectnessie/nessie"
   ports:
     - 19120:19120
  trino:
    image: trinodb/trino
    volumes:
      - ./trino/nessie.properties:/etc/trino/catalog/nessie.properties:ro
    ports:
      - 8080:8080
```

**nessie.properties**
```ini
connector.name=iceberg
iceberg.catalog.type=nessie
iceberg.nessie-catalog.uri=http://nessie:19120/api/v1
iceberg.nessie-catalog.default-warehouse-dir=/tmp

hive.azure.abfs-storage-account=<Storage account>
hive.azure.abfs-access-key=<Secret key>
```

I connect to Trino and run: 

```sql
create schema nessie.tabletest;
use nessie.tabletest;
create table test1(id int) with (location = 'abfs://landing@mydatalake.dfs.core.windows.net/landing-zone');
insert into test1 (id) values (2);
```
And this works, I can see the Iceberg tables created in my data lake. 
But I want to load external files into my lakehouse. I attempted this:

```sql
create table meters (_id varchar, name varchar) with (external_location = 'abfs://landing@mydatalake.dfs.core.windows.net/metry/landing-zone/meters.json', format = 'json');
```
Which gives me `Catalog 'nessie' table property 'external_location' does not exist`

So i try: 

```sql
create table meters (_id varchar, name varchar) with (location = 'abfs://landing@mydatalake.dfs.core.wind
ows.net/landing-zone.json', format = 'json');
```
Which returns `Unable to set catalog 'nessie' table property 'format' to ['json']: Invalid value [json]. Valid values: [ORC, PARQUET, AVRO]`

So I convert that JSON to Parquet and upload it.

```sql
create table meters (_id varchar, name varchar) with (location = 'abfs://landing@mydatalake.dfs.core.windows.net/landing-zone/meters.parquet', format = 'parquet');
```
With the result `--Cannot create a table on a non-empty location: <location>, set 'iceberg.unique-table-location=true' in your Iceberg catalog properties to use unique table locations for every table.`
