### DISCUSSION TITLE
Got exception: org.apache.hadoop.fs.UnsupportedFileSystemException No FileSystem for scheme "s3"

### DISCUSSION THREAD

**Discussion by AR-X4** [trinodb/trino#21372] [Q&A]
I'm trying to use the hive connector to create a table for parquet data in Wasabi s3.  Wasabi is AWS s3 compatible storage.  I'm using Trino 443 docker image.  When I try to create a table I receive the error 'No FileSystem for scheme "s3"'.

This is my hive.properties file:

connector.name=hive
fs.native-s3.enabled=true
s3.endpoint=https://s3.wasabisys.com
s3.aws-access-key=redacted
s3.aws-secret-key=redacted
s3.region=us-east-1
s3.path-style-access=true
hive.metastore.uri=thrift://host.docker.internal:9083

This is my command:

CREATE TABLE hive.default.test_table (
  Company VARCHAR,
  Ticker VARCHAR,
  FilingDate TIMESTAMP,
  PrimaryIndex VARCHAR,
  FilingMonth BIGINT,
  FilingYear BIGINT,
  FiscalQuarter BIGINT,
  FiscalYear BIGINT
)
WITH (
  format = 'PARQUET',
  external_location = 's3://trino-test/data/'
);

**Comment by AR-X4** [comment]
Seems like the issue might be with the Hive metastore service? Any documentation / additional configuration required for using a metastore service with s3?

2024-04-01T22:18:17.834Z	WARN	transaction-finishing-0	io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore	Rolling back due to metastore commit failure: Got exception: org.apache.hadoop.fs.UnsupportedFileSystemException No FileSystem for scheme "s3"

Metastore database:

docker run --rm -d --name postgres-metastore -p 5432:5432 -e POSTGRES_PASSWORD=redacted -v $PWD/pg-data:/var/lib/postgresql/data postgres

Metastore server:

docker run --rm -d -p 9083:9083 --env SERVICE_NAME=metastore --env VERBOSE=true --env DB_DRIVER=postgres --env SERVICE_OPTS="-Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://host.docker.internal:5432/metastore -Djavax.jdo.option.ConnectionUserName=hive -Djavax.jdo.option.ConnectionPassword=redacted" -v $PWD/postgresql-42.7.3.jar:/opt/hive/lib/postgresql-jdbc.jar --name metastore-service apache/hive:4.0.0

Trino:

docker run --rm --name trino -d -p 8080:8080 -v $PWD/catalog:/etc/trino/catalog trinodb/trino:443

**Comment by hashhar** [comment]
Your HMS seems to missing requires libraries to talk to S3 (or S3-compatible storage). Most likely it's the `hadoop-aws` JARs.

**Reply by kevinkurek** [reply]
Thanks for the insight!
For anyone else that ends up here with with docker-compose & minio & hive-metastore I had to create the environment and volumes like so. (Annotated with comments)

```
  hive-metastore:
    # Official Apache Hive 4 image (includes metastore service).
    image: apache/hive:4.0.0
    # Name the container so it’s easy to exec/logs against.
    container_name: hive-metastore
    environment:
      # Ask the image to run the metastore service (vs. CLI or hiveserver2).
      SERVICE_NAME: metastore
      # Hint that we use Postgres as the JDO backend (driver is provided below via JAR + hive-site.xml).
      DB_DRIVER: postgres

      # Point Hadoop/Hive to where core-site.xml is mounted (S3A/MinIO settings live there).
      # This tells the HMS how to access S3-compatible storage.
      HADOOP_CONF_DIR: /etc/hadoop/conf

      # Make sure Hadoop sees the S3A libraries (hadoop-aws + aws SDK).
      HADOOP_CLASSPATH: /opt/hadoop/share/hadoop/tools/lib/hadoop-aws-3.3.6.jar:/opt/hadoop/share/hadoop/tools/lib/aws-java-sdk-bundle-1.12.262.jar
      # Make sure Hive itself also sees those libs and the Postgres JDBC driver.
      HIVE_AUX_JARS_PATH: /opt/hive/lib/postgresql-42.7.3.jar,/opt/hadoop/share/hadoop/tools/lib/hadoop-aws-3.3.6.jar,/opt/hadoop/share/hadoop/tools/lib/aws-java-sdk-bundle-1.12.262.jar

    volumes:
      # Mount hive-site.xml (contains metastore URI and JDO/Postgres connection properties).
      # The image reads /opt/hive/conf automatically on startup.
      - ./hive/conf:/opt/hive/conf:ro # ro: read-only
      # Mount the Postgres JDBC driver so HMS can connect to the metastore DB.
      - ./hive/lib/postgresql-42.7.3.jar:/opt/hive/lib/postgresql-42.7.3.jar:ro
      # Mount Hadoop S3A connector JAR (needed if not bundled in the image).
      - ./jars/hadoop-aws-3.3.6.jar:/opt/hadoop/share/hadoop/tools/lib/hadoop-aws-3.3.6.jar:ro
      # Mount AWS SDK bundle used by S3A connector.
      - ./jars/aws-java-sdk-bundle-1.12.262.jar:/opt/hadoop/share/hadoop/tools/lib/aws-java-sdk-bundle-1.12.262.jar:ro
      # Mount Hadoop core-site.xml (defines fs.s3a.* endpoint/creds/path-style for MinIO).
      - ./hadoop/conf/core-site.xml:/etc/hadoop/conf/core-site.xml:ro
```
