### ISSUE TITLE
How to add annotations to service when using trino official helm chart

### ISSUE THREAD

**Issue by ashishjullia** [trinodb/trino#13085]
I've been struggling with adding the following annotations for my service type "LoadBalancer":
```
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
```

Is this supported yet, if yes/no how to achieve this? Please help me out.

**Comment by ashishjullia** [comment]
If someone else comes here in the near future, it can be achieved using the following code in `service.yaml`
```
apiVersion: v1
kind: Service
metadata:
  name: {{ template "trino.fullname" . }}
  labels:
    app: {{ template "trino.name" . }}
    chart: {{ template "trino.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "trino.name" . }}
    release: {{ .Release.Name }}
    component: coordinator
```

Related -> [PR](https://github.com/trinodb/charts/pull/10)
