### ISSUE TITLE
Can't enable external authentication on Kubernetes

### ISSUE THREAD

**Issue by m-ocean-it** [trinodb/trino#15528]
## Steps to reproduce

**1. Prepare own `values.yaml` to override values from Helm.**
```yaml
server:
  config:
    authenticationType: "PASSWORD"
  workerExtraConfig: "internal-communication.shared-secret=test"
  coordinatorExtraConfig: "internal-communication.shared-secret=test"
    
auth:
  passwordAuth: "admin:$2y$10$5fZ/HHz4VPMX3JzK9uqNEu962vDO0jtJge2Z8nKb2DORUX0r4RBWi"

additionalCatalogs:
  some_database.properties: |-
    connector.name=postgresql
    connection-url=jdbc:postgresql://some-db-hostname:5432/database_name
    connection-user=admin
    connection-password=some_password
```

**2. Install the chart**
```bash
helm install -f values.yaml my-trino trino/trino
```

**3. Make sure everything runs**

**4. Enable Ingress routing**
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trino-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - trino.my-own-domain.com
      secretName: trino-ingress-tls
  rules:
    - host: trino.my-own-domain.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: my-trino
              port:
                number: 8080
```
(I use the `cert-manager` add-on from MicroK8s to automatically generate TLS certificates.)

**5. Go to `trino.my-own-domain.com` to make sure routing is working and TLS is configured**

## The problem
- First of all, the web GUI displays `password not allowed` in the password field. I enter username "admin" and freely login into the dashboard.
- Then I connect to the SQL interface using DBeaver. I enter username "admin" and leave the password field empty. And... also, no problem. I can access everything I need in the connected catalog (`some_database.properties`).

So, yeah, no authentication whatsoever was enabled in the end and yet everything else works fine.

Am I doing something wrong?

**Comment by m-ocean-it** [comment]
`helm list`:
```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
my-trino        default         1               2022-12-26 17:59:22.059086203 +0000 UTC deployed        trino-0.8.0     375
```

**Comment by ashishjullia** [comment]
@m-ocean-it if you don't see a password enter the field when you try to access the trino ui on a browser's ui that means your ssl is not configured correctly.

```bash
Using TLS and a configured shared secret is required for password file authentication.
```

Ref: https://trino.io/docs/current/security/password-file.html

Note: SSL is required for password authentication.

**Comment by m-ocean-it** [comment]
I fixed it!

This had to be added to `coordinatorExtraConfig`: `http-server.process-forwarded=true`

So:
```yaml
server:
  config:
    authenticationType: "PASSWORD"
  workerExtraConfig: |-
    internal-communication.shared-secret=test
  coordinatorExtraConfig: |-
    internal-communication.shared-secret=test
    http-server.process-forwarded=true

auth:
  passwordAuth: "admin:<hashed_password>"
```
