### ISSUE TITLE
Password authentication for Trino behind external proxy/load balancer

### ISSUE THREAD

**Issue by Subhashini2610** [trinodb/trino#16508]
I have deployed Trino on K8s using the helm chart. This Trino is behind an external nginx proxy which handles the TLS certs. The nginx layer forwards the request to Trino service (of type Cluster IP) using Ingress objects. 
The problem with this setup is that I am unable to provide a password in the web-ui,  although I have configured my Helm chart with the password file as below:
```
server:
  config:
    authenticationType: "PASSWORD"
  workerExtraConfig: "internal-communication.shared-secret=test"
  coordinatorExtraConfig: "internal-communication.shared-secret=test"
    
auth:
  passwordAuth: "test:<some hash>"
```
The web UI shows the password field with text '_Password not allowed_'

According to your [documentation](https://trino.io/docs/current/security/tls.html#use-a-load-balancer-to-terminate-tls-https), I need to add the following to coordinator's config.properties file:
```
http-server.process-forwarded=true
```

However, when I add this, I am no longer able to see the web UI. It says bowser is disabled. Moreover, with the above configuration added, I am not able to connect to my Trino server from other clients like DBeaver. 

I do need a password based authentication as I need to connect Immuta to Trino and Immuta has the password as a mandatory field during connection. Please help.
