### ISSUE TITLE
Memory Based autoscaler

### ISSUE THREAD

**Issue by moelhoussein** [trinodb/trino#18739]
Trino Helm chart currently only has a CPU based autoscaler. From the POC's we've done so far with our data teams CPU usage is negligible compared to memory. Can we add a memory based auto-scaler to the helm chart?

Let me know if I can go ahead and create a PR for this.

**Comment by zubairAmperity** [comment]
have you made any progress on this, or found any alternatives?

**Comment by moelhoussein** [comment]
we ended up, forking the chart and making our own changes to it.
Here is the proposed change to the `autoscaler.yaml`

```
{{- if .Values.server.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "trino.worker" . }}
  {{- if .Values.commonLabels }}
  labels:
    {{- tpl (toYaml .Values.commonLabels) . | nindent 4 }}
  {{- end }}
spec:
  maxReplicas: {{ .Values.server.autoscaling.maxReplicas }}
  minReplicas: {{ .Values.server.workers }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "trino.worker" . }}
  metrics:
  {{- if eq .Values.server.autoscaling.type "CPU"}}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  {{- end }}      
  {{- if eq .Values.server.autoscaling.type "memory"}}      
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60
  {{- end }}
{{- end }}
```
