### ISSUE TITLE
Password file authentication does not work using ingress https

### ISSUE THREAD

**Issue by andreyolv** [trinodb/trino#18781]
I follow this [doc](https://trino.io/docs/current/security/tls.html#use-a-load-balancer-to-terminate-tls-https)

I created a user 'admin' with password 'teste', but I can not login in UI. By cli also does not work

I'm trying run Trino on Kubernetes using official helm chart with values:
```
    server:
      config:
        authenticationType: "PASSWORD"
      workerExtraConfig: |-
        internal-communication.shared-secret=test
      coordinatorExtraConfig: |-
        internal-communication.shared-secret=test
        http-server.process-forwarded=true
    auth: 
      passwordAuth: |- 
        admin:$2a$10$k7ISe/n5TicAp4h1UtFU4u.bcCcEOpmCo/1Uuo/xIoAmTsywmRO2S
    accessControl:
      type: configmap
      refreshPeriod: 60s
      rules:
        rules.json: |-
          {
            "catalogs": [
              {
                "user": "admin",
                "allow": "all"
              }
            ],
            "schemas": [
              {
                "user": "admin",
                "owner": true
              }
            ],
            "tables": [
              {
                "user": "admin",
                "privileges": ["SELECT", "INSERT", "DELETE", "UPDATE", "OWNERSHIP"]
              }
            ]
          }

```

My ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trino
  namespace: trino
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - 'XXXXXXXXXXXXX'
    secretName: XXXXXXXXXXXXXX
  rules:
  - host: trino.xxxx
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service: 
            name: trino
            port:
              number: 8080
```

When I access UI on my host 'trino.xxxx' and try login using user 'admin' and password 'teste' the login page is refreshed but remains in the same login page. If I try a user that does not exist, the same thing happns.

By trino cli, also does not work. Example, the command:
```
./trino --server https://trino.xxx --user=admin --password
```
Apparently it logs in but nothing runs. All return this error:
Error running command: java.net.SocketTimeoutException: Connect timed out

Also, If I try a user and password that does not exist, the same thing happns.

Does anyone have an idea what the problem is?
