### ISSUE TITLE
ElasticSeach Connector not using environment variables for secrets

### ISSUE THREAD

**Issue by cunrein** [trinodb/trino#19514]
**This has been resolved**

[According to the Secrets doc](https://trino.io/docs/current/security/secrets.html) one can set secrets in environment variables using `export DB_PASSWORD=password` and then pull that using `${ENV:DB_PASSWORD}` in the properties file, however when deploying into kubernetes this is not working. A key error is always produced. It appears that the substitution is not taking place. 

Addition to the `configmap-catalog.yaml`:
```
elasticsearch.properties: |
    connector.name=elasticsearch
    elasticsearch.security=PASSWORD
    elasticsearch.host=elastic-1.dev
    elasticsearch.port=9200
    elasticsearch.auth.user=${ENV:ELASTIC_USER}
    elasticsearch.auth.password=${ENV:ELASTIC_PASSWORD}
    elasticsearch.tls.enabled=true
    elasticsearch.tls.keystore-path=${ENV:KEYSTORE_PATH}
    elasticsearch.tls.truststore-path=${ENV:TRUSTSTORE_PATH}
    elasticsearch.tls.keystore-password=${ENV:KEYSTORE_PASSWORD}
    elasticsearch.tls.truststore-password=${ENV:TRUSTSTORE_PASSWORD}
```
If plain text usernames, passwords and paths are used the pod deploys correctly. The environment variables with the values are being set per these additions to the `values.yaml`
```
secret:
  name: trino-secrets
  keystore: [redacted]
  keystorePassword: [redacted]
  keystorePath: [redacted]
  truststore: [redacted]
  truststorePassword: [redacted]
  truststorePath: [redacted]
  elasticUser: [redacted]
  elasticPassword: [redacted]
env:  
  - name: KEYSTORE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "trino-secrets"
        key: "keystorePassword"
  - name: TRUSTSTORE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "trino-secrets"
        key: "truststorePassword"
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "trino-secrets"
        key: "elasticPassword"
  - name: ELASTIC_USER
    valueFrom:
      secretKeyRef:
        name: "trino-secrets"
        key: "elasticUser"
  - name: KEYSTORE_PATH
    valueFrom:
      secretKeyRef:
        name: "trino-secrets"
        key: "keystorePath"
  - name: TRUSTSTORE_PATH
    valueFrom:
      secretKeyRef:
        name: "trino-secrets"
        key: "truststorePath"
```
An additonal `trino-secrets.yaml` was also created:
```
apiVersion: v1
kind: Secret
metadata:
  name: trino-secrets
  defaultMode: 511
  labels:
    {{- include "trino.labels" . | nindent 4 }}
type: Opaque
data:      
  keystore.jks: {{ .Values.secret.keystore }}
  keystorePath: {{ .Values.secret.keystorePath }}
  keystorePassword: {{ .Values.secret.keystorePassword }}
  truststore.jks: {{ .Values.secret.truststore }}
  truststorePath: {{ .Values.secret.keystorePath }}
  truststorePassword: {{ .Values.secret.truststorePassword }}
  elasticUser: {{ .Values.secret.elasticUser }}
  elasticPassword: {{ .Values.secret.elasticPassword }}
```
When the charts are tested via `helm3 template . -f values.yaml` they are correct. When you exec into the pod the `elasticsearch.properties` is correct and all environment variables needed for the properties file have been set. 

Trino version: 426 pulled from docker.io
K8s version: 1.26.9
