### ISSUE TITLE
Ingest data from Azure Blob Storage without a Hive metastore

### ISSUE THREAD

**Issue by delsehi** [trinodb/trino#20327]
I'm trying to setup Trino with Nessie for creating a data lakehouse with Iceberg tables. I want to ingest data (csv, json, etc) with Trino and load the Iceberg tables (ELT with Trino). 

I've played around with a Docker-compose file: 

```yaml
version: '3.9'

services:
  nessie:
   image: "ghcr.io/projectnessie/nessie"
   ports:
     - 19120:19120
  trino:
    image: trinodb/trino
    volumes:
      - ./trino/nessie.properties:/etc/trino/catalog/nessie.properties:ro
    ports:
      - 8080:8080
```
And I mount a volume with properties: 
```
connector.name=iceberg
iceberg.catalog.type=nessie 
iceberg.nessie-catalog.uri=http://nessie:19120/api/v1
iceberg.nessie-catalog.default-warehouse-dir=/tmp

hive.azure.wasb-storage-account=<The name of my storage account>
hive.azure.wasb-access-key=<My secret key>
```

I cannot figure out how to query a file though and add it. 

I've tried creating schemas like 
```sql
CREATE SCHEMA nessie.mytest WITH ( location = 'wasb://containerName@mystorageaccount.blob.windows.net/somepath');
CREATE TABLE nessie.mytest.testing (name varchar);
```

But I realize this might not work since I'm using Nessie. 
I want to avoid setting up a Hive metastore for the only sake of accessing the data before loading it into Iceberg tables + Nessie. 
Is there any way of doing that or am I really thinking of Trino in the wrong way?
