### ISSUE TITLE
Trino jmx metric exists in connctor but lost in ingress

### ISSUE THREAD

**Issue by dishkakrauch** [trinodb/trino#20775]
Hi there.

Can anybody help us with understanding the reason of lost Java metrics in jmx?

We have set up trino with helm, configured it with our requirements. Then we faced strange Java metric attitude: jmx exporter works perfectly fine with many metrics, ingress shows them, but not all. We also set up connector to jmx for checking if lost metrics exist.

For example we can select Java free physical memory metrics as it is in settings config.yaml but it's not accessible with ingress. Can someone help me to understand why?

![Screenshot_20240220_114354_Teams](https://github.com/trinodb/trino/assets/34490641/04fe2f5f-f07c-4e2c-a0da-4183f3a8ed06)
![Screenshot_20240220_114401_Teams](https://github.com/trinodb/trino/assets/34490641/07c36292-e6b6-46f3-8966-2971aad83260)
![Screenshot_20240220_114406_Teams](https://github.com/trinodb/trino/assets/34490641/4814f8e4-1022-4b64-8658-2e3ddb82a134)
![Screenshot_20240220_114411_Teams](https://github.com/trinodb/trino/assets/34490641/8c67c36d-534d-4ac3-83b2-15dfeba069ea)
![Screenshot_20240220_114416_Teams](https://github.com/trinodb/trino/assets/34490641/21bb106f-4c53-4051-bcaf-0d2359492706)

**Comment by hashhar** [comment]
you're possibly hitting https://github.com/trinodb/trino/pull/16038

**Comment by dishkakrauch** [comment]
Didn't help unfortunatelly.
Here is config.yaml:

```
#---
#startDelaySeconds: 0
#ssl: false
#lowercaseOutputName: false
#lowercaseOutputLabelNames: false
# By default, the JMX exporter works through all available mbeans, which is very slow
# So we whitelist the objects we're going to scrape, which makes scraping 120x faster (measured!)
whitelistObjectNames:
  - "io.airlift.node:name=NodeInfo"
  - "java.nio:type=BufferPool,*"
  - "java.lang=*"
  - "trino.execution.executor:name=TaskExecutor"
  - "trino.execution:name=QueryManager"
  - "trino.execution:name=SqlTaskManager"
  - "trino.failuredetector:name=HeartbeatFailureDetector"
  - "trino.memory:type=ClusterMemoryPool,name=general"
  - "io.trino.hdfs.s3:*"
  - "trino.plugin.deltalake.transactionlog:*"
  - "trino.sql.planner.iterative:*"
  - "trino.sql.planner.optimizations:*"
 
# When adding new rules, don't forget to whitelist their object names or they won't get scraped properly
rules:
  # Cluster metrics
  - pattern: trino.failuredetector<name=HeartbeatFailureDetector><>ActiveCount
    name: trino_active_nodes
    cache: true
  - pattern: trino.failuredetector<name=HeartbeatFailureDetector><>FailedCount
    name: trino_failed_nodes
    cache: true
  - pattern: trino.memory<type=ClusterMemoryPool, name=general><>TotalDistributedBytes
    name: trino_cluster_total_distributed_bytes
    cache: true
  - pattern: trino.memory<type=ClusterMemoryPool, name=general><>ReservedDistributedBytes
    name: trino_cluster_reserved_distributed_bytes
    cache: true
  - pattern: trino.memory<type=ClusterMemoryPool, name=general><>FreeDistributedBytes
    name: trino_cluster_free_memory
    cache: true
 
  # Node info
  - pattern: io.airlift.node<name=NodeInfo><>NodeId
    name: trino_node_id
    cache: true
  - pattern: io.airlift.node<name=NodeInfo><>InstanceId
    name: trino_node_instance_id
    cache: true
  - pattern: io.airlift.node<name=NodeInfo><>InternalAddress
    name: trino_node_internal_address
    cache: true
  - pattern: io.airlift.node<name=NodeInfo><>Pool
    name: trino_node_pool
    cache: true
  - pattern: io.airlift.node<name=NodeInfo><>StartTime
    name: trino_node_start_time
    cache: true

  # Java metrics
  - pattern: 'java.lang<name=G1 Old Generation, type=GarbageCollector><>CollectionCount: (\d+)'
    name: g1_old_collection_count
    cache: true
  - pattern: 'java.lang<name=G1 Young Generation, type=GarbageCollector><>CollectionCount: (\d+)'
    name: g1_young_collection_count
    cache: true
  - pattern: 'java.lang<name=G1 Old Generation, type=GarbageCollector><>CollectionTime: (\d+)'
    name: g1_old_collection_time
    cache: true
  - pattern: 'java.lang<name=G1 Young Generation, type=GarbageCollector><>CollectionTime: (\d+)'
    name: g1_young_collection_time
    cache: true
  - pattern: 'java.lang<type=Memory><HeapMemoryUsage>(.+): .*'
    name: java_lang_Memory_HeapMemoryUsage
    cache: true
  - pattern: 'java.lang<type=Memory><NonHeapMemoryUsage>(.+): .*'
    name: java_lang_Memory_NonHeapMemoryUsage
    cache: true
  - pattern: 'java.lang<type=OperatingSystem><FreePhysicalMemorySize>(.+): .*'
    name: java_lang_OperatingSystem_FreePhysicalMemorySize
    cache: true
  - pattern: 'java.lang<type=OperatingSystem><TotalPhysicalMemorySize>(.+): .*'
    name: java_lang_OperatingSystem_TotalPhysicalMemorySize
    cache: true
  - pattern: 'java.lang<type=OperatingSystem><TotalSwapSpaceSize>(.+): .*'
    name: java_lang_OperatingSystem_TotalSwapSpaceSize
    cache: true
  - pattern: 'java.lang<type=OperatingSystem><SystemCpuLoad>(.+): .*'
    name: java_lang_OperatingSystem_SystemCpuLoad
    cache: true
  - pattern: 'java.lang<type=OperatingSystem><AvailableProcessors>(.+): .*'
    name: java_lang_OperatingSystem_AvailableProcessors
    cache: true    
  - pattern: 'java.nio<name=direct, type=BufferPool><>MemoryUsed: (\d+)'
    name: java_nio_direct_MemoryUsed
    cache: true
  - pattern: 'java.lang<type=OperatingSystem><.*>OpenFileDescriptorCount: .*'
    name: java_lang_OperatingSystem_OpenFileDescriptorCount
    cache: true
  - pattern: 'java.lang<type=OperatingSystem><.*>ProcessCpuLoad: .*'
    name: java_lang_OperatingSystem_ProcessCpuLoad
    cache: true
  - pattern: 'java.lang<type=Threading><(.*)>ThreadCount: .*'
    name: java_lang_Threading_ThreadCount
    cache: true
 
  # Query Manager
  - pattern: trino.execution<name=QueryManager><>RunningQueries
    name: trino_running_queries
    cache: true
  - pattern: trino.execution<name=QueryManager><>QueuedQueries
    name: trino_queued_queries
    cache: true
  - pattern: trino.execution<name=QueryManager><>CompletedQueries.TotalCount
    name: trino_completed_queries_count_total
    cache: true
  - pattern: trino.execution<name=QueryManager><>CanceledQueries.TotalCount
    name: trino_canceled_queries_count_total
    cache: true
  - pattern: trino.execution<name=QueryManager><>FailedQueries.TotalCount
    name: trino_failed_queries_count_total
    cache: true
  - pattern: trino.execution<name=QueryManager><>ExecutionTime.OneMinute.P50
    name: trino_execution_time_one_minute_p50
    cache: true
  - pattern: trino.execution<name=QueryManager><>ExecutionTime.OneMinute.P90
    name: trino_execution_time_one_minute_p90
    cache: true
  - pattern: trino.execution<name=QueryManager><>ExecutionTime.OneMinute.P99
    name: trino_execution_time_one_minute_p99
    cache: true
  - pattern: trino.execution<name=QueryManager><>QueuedTime.OneMinute.P50
    name: trino_queued_time_one_minute_p50
    cache: true
  - pattern: trino.execution<name=QueryManager><>QueuedTime.OneMinute.P90
    name: trino_queued_time_one_minute_p90
    cache: true
  - pattern: trino.execution<name=QueryManager><>QueuedTime.OneMinute.P99
    name: trino_queued_time_one_minute_p99
    cache: true
  - pattern: trino.execution<name=QueryManager><>StartedQueries.OneMinute.Count
    name: trino_started_queries_one_minute
    cache: true
  - pattern: trino.execution<name=QueryManager><>CompletedQueries.OneMinute.Count
    name: trino_completed_queries_one_minute
    cache: true
  - pattern: trino.execution<name=QueryManager><>CanceledQueries.OneMinute.Count
    name: trino_canceled_queries_one_minute
    cache: true
  - pattern: trino.execution<name=QueryManager><>AbandonedQueries.OneMinute.Count
    name: trino_abandoned_queries_one_minute
    cache: true
  - pattern: trino.execution<name=QueryManager><>InternalFailures.OneMinute.Count
    name: trino_failed_queries_internal_one_minute
    cache: true
  - pattern: trino.execution<name=QueryManager><>ExternalFailures.OneMinute.Count
    name: trino_failed_queries_external_one_minute
    cache: true
  - pattern: trino.execution<name=QueryManager><>UserErrorFailures.OneMinute.Count
    name: trino_failed_queries_user_one_minute
    cache: true
  - pattern: trino.execution<name=QueryManager><>ExecutionTime.FiveMinutes.P50
    name: trino_execution_time_five_minute_p50
    cache: true
  - pattern: trino.execution<name=QueryManager><>ExecutionTime.FiveMinutes.P90
    name: trino_execution_time_five_minute_p90
    cache: true
  - pattern: trino.execution<name=QueryManager><>ExecutionTime.FiveMinutes.P99
    name: trino_execution_time_five_minute_p99
    cache: true
  - pattern: trino.execution<name=QueryManager><>QueuedTime.FiveMinutes.P50
    name: trino_queued_time_five_minute_p50
    cache: true
  - pattern: trino.execution<name=QueryManager><>QueuedTime.FiveMinutes.P90
    name: trino_queued_time_five_minute_p90
    cache: true
  - pattern: trino.execution<name=QueryManager><>QueuedTime.FiveMinutes.P99
    name: trino_queued_time_five_minute_p99
    cache: true
  - pattern: trino.execution<name=QueryManager><>StartedQueries.FiveMinute.Count
    name: trino_started_queries_five_minute
    cache: true
  - pattern: trino.execution<name=QueryManager><>CompletedQueries.FiveMinute.Count
    name: trino_completed_queries_five_minute
    cache: true
  - pattern: trino.execution<name=QueryManager><>CanceledQueries.FiveMinute.Count
    name: trino_canceled_queries_five_minute
    cache: true
  - pattern: trino.execution<name=QueryManager><>AbandonedQueries.FiveMinute.Count
    name: trino_abandoned_queries_five_minute
    cache: true
  - pattern: trino.execution<name=QueryManager><>InternalFailures.FiveMinute.Count
    name: trino_failed_queries_internal_five_minute
    cache: true
  - pattern: trino.execution<name=QueryManager><>ExternalFailures.FiveMinute.Count
    name: trino_failed_queries_external_five_minute
    cache: true
  - pattern: trino.execution<name=QueryManager><>UserErrorFailures.FiveMinute.Count
    name: trino_failed_queries_user_five_minute
    cache: true
  - pattern: trino.execution<name=QueryManager><>ConsumedCpuTimeSecs.TotalCount
    name: trino_consumed_cpu_time_sec_total
    cache: true
  - pattern: trino.execution<name=QueryManager><>ConsumedInputBytes.TotalCount
    name: trino_consumed_input_bytes_total
    cache: true
  - pattern: trino.execution<name=QueryManager><>ConsumedInputRows.TotalCount
    name: trino_consumed_input_rows_total
    cache: true
  - pattern: trino.execution<name=QueryManager><>ExecutionTime.AllTime.Avg
    name: trino_execution_time_all_time_avg
    cache: true
  - pattern: trino.execution<name=QueryManager><>ExecutionTime.AllTime.Count
    name: trino_execution_time_all_time_count
    cache: true
  - pattern: trino.execution<name=QueryManager><>ExecutionTime.AllTime.P50
    name: trino_execution_time_all_time_p50
    cache: true
  - pattern: trino.execution<name=QueryManager><>ExecutionTime.AllTime.P90
    name: trino_execution_time_all_time_p90
    cache: true
  - pattern: trino.execution<name=QueryManager><>ExecutionTime.AllTime.P99
    name: trino_execution_time_all_time_p99
    cache: true
 
  # Task Manager
  - pattern: trino.execution<name=SqlTaskManager><>InputDataSize.OneMinute.Count
    name: trino_task_input_bytes_one_minute
    cache: true
  - pattern: trino.execution<name=SqlTaskManager><>InputPositions.OneMinute.Count
    name: trino_task_input_one_minute
    cache: true
  - pattern: trino.execution<name=SqlTaskManager><>OutputDataSize.OneMinute.Count
    name: trino_task_output_bytes_one_minute
    cache: true
  - pattern: trino.execution<name=SqlTaskManager><>OutputPositions.OneMinute.Count
    name: trino_task_output_rows_one_minute
    cache: true
  - pattern: trino.execution.executor<name=TaskExecutor><>ProcessorExecutor.ActiveCount
    name: trino_task_active_count
    cache: true
  - pattern: trino.execution.executor<name=TaskExecutor><>ProcessorExecutor.CompletedTaskCount
    name: trino_task_completed_count
    cache: true
  - pattern: trino.execution.executor<name=TaskExecutor><>ProcessorExecutor.QueuedTaskCount
    name: trino_task_queued_count
    cache: true
 
  # Connector metrics for individual catalogs
  - pattern: io.trino.hdfs.s3<type=TrinoS3FileSystem, name=(\w+)><>ActiveConnections.TotalCount
    name: trino_$1_s3_active_connections_count_total
    cache: true
  - pattern: io.trino.hdfs.s3<type=TrinoS3FileSystem, name=(\w+)><>AwsAbortedExceptions.TotalCount
    name: trino_$1_s3_aws_aborted_exceptions_count_total
    cache: true
  - pattern: io.trino.hdfs.s3<type=TrinoS3FileSystem, name=(\w+)><>AwsRequestCount.TotalCount
    name: trino_$1_s3_aws_request_count_total
    cache: true
  - pattern: io.trino.hdfs.s3<type=TrinoS3FileSystem, name=(\w+)><>AwsRequestTime.AllTime.Count
    name: trino_$1_s3_aws_request_time_total
    cache: true
  - pattern: io.trino.hdfs.s3<type=TrinoS3FileSystem, name=(\w+)><>AwsRetryCount.TotalCount
    name: trino_$1_s3_aws_retry_count_total
    cache: true
  - pattern: io.trino.hdfs.s3<type=TrinoS3FileSystem, name=(\w+)><>AwsThrottleExceptions.TotalCount
    name: trino_$1_s3_aws_throttle_exception_count_total
    cache: true
  - pattern: io.trino.hdfs.s3<type=TrinoS3FileSystem, name=(\w+)><>GetMetadataErrors.TotalCount
    name: trino_$1_s3_get_metadata_errors_count_total
    cache: true
  - pattern: io.trino.hdfs.s3<type=TrinoS3FileSystem, name=(\w+)><>GetMetadataRetries.TotalCount
    name: trino_$1_s3_get_metadata_retries_count_total
    cache: true
  - pattern: io.trino.hdfs.s3<type=TrinoS3FileSystem, name=(\w+)><>GetObjectErrors.TotalCount
    name: trino_$1_s3_get_object_errors_count_total
    cache: true
  - pattern: io.trino.hdfs.s3<type=TrinoS3FileSystem, name=(\w+)><>GetObjectRetries.TotalCount
    name: trino_$1_s3_get_object_retries_count_total
    cache: true
  - pattern: io.trino.hdfs.s3<type=TrinoS3FileSystem, name=(\w+)><>ListLocatedStatusCalls.TotalCount
    name: trino_$1_s3_list_located_status_calls_count_total
    cache: true
  - pattern: io.trino.hdfs.s3<type=TrinoS3FileSystem, name=(\w+)><>ListObjectsCalls.TotalCount
    name: trino_$1_s3_list_objects_calls_count_total
    cache: true
  - pattern: io.trino.hdfs.s3<type=TrinoS3FileSystem, name=(\w+)><>ListStatusCalls.TotalCount
    name: trino_$1_s3_list_status_calls_count_total
    cache: true
  - pattern: io.trino.hdfs.s3<type=TrinoS3FileSystem, name=(\w+)><>MetadataCalls.TotalCount
    name: trino_$1_s3_metadata_calls_count_total
    cache: true
  - pattern: io.trino.hdfs.s3<type=TrinoS3FileSystem, name=(\w+)><>OtherReadErrors.TotalCount
    name: trino_$1_s3_other_read_errors_count_total
    cache: true
  - pattern: io.trino.hdfs.s3<type=TrinoS3FileSystem, name=(\w+)><>ReadRetries.TotalCount
    name: trino_$1_s3_read_retries_count_total
    cache: true
  - pattern: io.trino.hdfs.s3<type=TrinoS3FileSystem, name=(\w+)><>SocketExceptions.TotalCount
    name: trino_$1_s3_socket_exceptions_count_total
    cache: true
  - pattern: io.trino.hdfs.s3<type=TrinoS3FileSystem, name=(\w+)><>SocketTimeoutExceptions.TotalCount
    name: trino_$1_s3_socket_timeout_exceptions_count_total
    cache: true
  - pattern: io.trino.hdfs.s3<type=TrinoS3FileSystem, name=(\w+)><>StartedUploads.TotalCount
    name: trino_$1_s3_started_uploads_count_total
    cache: true
  - pattern: io.trino.hdfs.s3<type=TrinoS3FileSystem, name=(\w+)><>SuccessfulUploads.TotalCount
    name: trino_$1_s3_successful_uploads_count_total
    cache: true
  - pattern: trino.plugin.deltalake.transactionlog<type=TransactionLogAccess, name=(\w+), catalog=(\w+)><>DataFileMetadataCacheStats.HitRate
    name: trino_$1_transaction_log_data_file_metadata_cache_hit_rate
    cache: true
  - pattern: trino.plugin.deltalake.transactionlog<type=TransactionLogAccess, name=(\w+), catalog=(\w+)><>DataFileMetadataCacheStats.MissRate
    name: trino_$1_transaction_log_data_file_metadata_cache_miss_rate
    cache: true
  - pattern: trino.plugin.deltalake.transactionlog<type=TransactionLogAccess, name=(\w+), catalog=(\w+)><>DataFileMetadataCacheStats.RequestCount
    name: trino_$1_transaction_log_data_file_metadata_cache_request_count
    cache: true
  - pattern: trino.plugin.deltalake.transactionlog<type=TransactionLogAccess, name=(\w+), catalog=(\w+)><>MetadataCacheStats.HitRate
    name: trino_$1_transaction_log_metadata_cache_hit_rate
    cache: true
  - pattern: trino.plugin.deltalake.transactionlog<type=TransactionLogAccess, name=(\w+), catalog=(\w+)><>MetadataCacheStats.MissRate
    name: trino_$1_transaction_log_metadata_cache_miss_rate
    cache: true
  - pattern: trino.plugin.deltalake.transactionlog<type=TransactionLogAccess, name=(\w+), catalog=(\w+)><>MetadataCacheStats.RequestCount
    name: trino_$1_transaction_log_metadata_cache_request_count
    cache: true
 
  # Planner metrics
  - pattern: trino.sql.planner.optimizations<name=PlanOptimizer, optimizer=(\w+)><>Failures
    name: trino_sql_planner_planoptimizer_$1_failures
    cache: true
  - pattern: trino.sql.planner.optimizations<name=PlanOptimizer, optimizer=(\w+)><>Time.Count
    name: trino_sql_planner_planoptimizer_$1_time_count
    cache: true
  - pattern: trino.sql.planner.optimizations<name=PlanOptimizer, optimizer=(\w+)><>Time.Avg
    name: trino_sql_planner_planoptimizer_$1_time_avg
    cache: true
  - pattern: trino.sql.planner.optimizations<name=PlanOptimizer, optimizer=(\w+)><>Time.P50
    name: trino_sql_planner_planoptimizer_$1_time_p50
    cache: true
  - pattern: trino.sql.planner.optimizations<name=PlanOptimizer, optimizer=(\w+)><>Time.P90
    name: trino_sql_planner_planoptimizer_$1_time_p90
    cache: true
  - pattern: trino.sql.planner.optimizations<name=PlanOptimizer, optimizer=(\w+)><>Time.P99
    name: trino_sql_planner_planoptimizer_$1_time_p99
    cache: true
  - pattern: trino.sql.planner.iterative<name=name=IterativeOptimizer, rule=(\w+)><>Failures
    name: trino_sql_planner_iterativeoptimizer_$1_failures
    cache: true
  - pattern: trino.sql.planner.iterative<name=name=IterativeOptimizer, rule=(\w+)><>Hits
    name: trino_sql_planner_iterativeoptimizer_$1_hits
    cache: true
  - pattern: trino.sql.planner.iterative<name=name=IterativeOptimizer, rule=(\w+)><>Invocations
    name: trino_sql_planner_iterativeoptimizer_$1_invocations
    cache: true
  - pattern: trino.sql.planner.iterative<name=name=IterativeOptimizer, rule=(\w+)><>Time.Count
    name: trino_sql_planner_iterativeoptimizer_$1_time_count
    cache: true
  - pattern: trino.sql.planner.iterative<name=name=IterativeOptimizer, rule=(\w+)><>Time.Avg
    name: trino_sql_planner_iterativeoptimizer_$1_time_avg
    cache: true
  - pattern: trino.sql.planner.iterative<name=name=IterativeOptimizer, rule=(\w+)><>Time.P50
    name: trino_sql_planner_iterativeoptimizer_$1_time_p50
    cache: true
  - pattern: trino.sql.planner.iterative<name=name=IterativeOptimizer, rule=(\w+)><>Time.P90
    name: trino_sql_planner_iterativeoptimizer_$1_time_p90
    cache: true
  - pattern: trino.sql.planner.iterative<name=name=IterativeOptimizer, rule=(\w+)><>Time.P99
    name: trino_sql_planner_iterativeoptimizer_$1_time_p99
    cache: true
```
