### ISSUE TITLE
[Support] Need Help with Kubernetes and Trino Setup 

### ISSUE THREAD

**Issue by soumilshah1995** [trinodb/trino#21956]
Hello I am trying to run K8 and trino locally 
and I am following the guide listed here https://trino.io/docs/current/installation/kubernetes.html

```
helm repo add trino https://trinodb.github.io/charts
helm install example-trino-cluster trino/trino

POD_NAME=$(kubectl get pods -l "app=trino,release=example-trino-cluster,component=coordinator" -o name)
kubectl port-forward $POD_NAME 8080:8080
```

Example.yaml

```
image:
  tag: "447"
server:
  workers: 3
coordinator:
  jvm:
    maxHeapSize: "8G"
worker:
  jvm:
    maxHeapSize: "8G"
```

helm upgrade example-trino-cluster trino/trino -f example.yaml

![image](https://github.com/trinodb/trino/assets/39345855/afdc8771-0ad4-414b-b1f4-f6fd7a9d2119)

Not sure why I dont see workers here everything looks good to me not sure what stop im missing here
