### ISSUE TITLE
Flaky Exasol connector CI

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#22698]
https://github.com/trinodb/trino/actions/runs/9965297128/job/27535676350?pr=22696

**Comment by kaklakariada** [comment]
To get details logs from the Exasol database and JDBC driver, do the following:
1. In `ExasolClientModule.connectionFactory()` enable debug log for the JDBC driver:
    ```java
        // Enable debug logging for the Exasol JDBC driver to investigate flaky tests
        connectionProperties.setProperty("debug", "1");
        connectionProperties.setProperty("logdir", "/tmp/exasol-jdbc-log/");
    ```
2. In `ci.yml`: create directory for JDBC driver logs **before** running the tests:
    ```yml
      - name: Create dir for Exasol JDBC driver logs
        run: mkdir -p /tmp/exasol-jdbc-log/
    ```
3. In `ci.yml`: collect and upload logs **after** running the tests:
    ```yml
      - name: Print disk space after tests
        if: ${{ always() }}
        run: df -h
      - name: "Generate Unique Artifact Name"
        if: ${{ always() }}
        run: echo "UNIQUE_NAME=$RANDOM" >> $GITHUB_ENV
      - name: "Upload Exasol JDBC driver logs"
        uses: actions/upload-artifact@v4
        if: ${{ always() && contains(matrix.modules, 'plugin/trino-exasol') }}
        with:
          path: /tmp/exasol-jdbc-log/
          name: exasol-jdbc-log-${{ env.UNIQUE_NAME }}
          retention-days: 3
          if-no-files-found: error
      - name: Extract DB logs from Docker container
        if: ${{ always() && contains(matrix.modules, 'plugin/trino-exasol') }}
        run: |
          docker ps
          CONTAINER_NAME=$(docker ps --filter "ancestor=exasol/docker-db:8.27.0" --format "{{.Names}}")
          mkdir -p /tmp/db-log/
          docker cp "$CONTAINER_NAME:/exa/logs/" /tmp/db-log/
      - name: "Upload Exasol Docker-DB logs"
        uses: actions/upload-artifact@v4
        if: ${{ always() && contains(matrix.modules, 'plugin/trino-exasol') }}
        with:
          path: /tmp/db-log/
          name: exasol-db-log-${{ env.UNIQUE_NAME }}
          retention-days: 3
          if-no-files-found: error
    ```
4. Remove other builds from the matrix and add multiple instances of the Exasol module:
    ```yml
      - name: Set matrix
        id: set-matrix
        run: |
          # GIB doesn't run on master, so make sure the file always exist
          touch gib-impacted.log
          cat <<EOF > .github/test-matrix.yaml
          include:
            - modules:
                - client/trino-jdbc
                - plugin/trino-base-jdbc
                - plugin/trino-memory
                - plugin/trino-thrift
            - modules:
                - lib/trino-orc
                - lib/trino-parquet
            - modules:
                - lib/trino-filesystem
                - lib/trino-filesystem-azure
                - lib/trino-filesystem-manager
                - lib/trino-filesystem-s3
                - lib/trino-hdfs
            - { modules: plugin/trino-exasol }
            - { modules: plugin/trino-exasol }
            - { modules: plugin/trino-exasol }
            - { modules: plugin/trino-exasol }
            - { modules: plugin/trino-exasol }
            - { modules: plugin/trino-exasol }
            - { modules: plugin/trino-exasol }
            - { modules: plugin/trino-exasol }
            - { modules: plugin/trino-exasol }
            - { modules: plugin/trino-exasol }
          EOF
          ./.github/bin/build-matrix-from-impacted.py -v -i gib-impacted.log -m .github/test-matrix.yaml -o matrix.json
          echo "Matrix: $(jq '.' matrix.json)"
          echo "matrix=$(jq -c '.' matrix.json)" >> $GITHUB_OUTPUT
    ```

Notes:
* Adapt Exasol Docker image name `exasol/docker-db:8.27.0` to current version defined in `TestingExasolServer`
* Trigger the build with `git commit --allow-empty -m "Trigger build" && git push`
