### ISSUE TITLE
Trino Fails to Handle Path-Based Routing with NGINX Ingress Controller 

### ISSUE THREAD

**Issue by shwetajha25** [trinodb/trino#23028]
ingress.yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "360"
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: trino287663-coordinator
  namespace: <namespace>
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: trino287663
            port:
              number: 8080
        path: /trino287663
        pathType: Prefix

**Comment by wendigo** [comment]
Can you elaborate what's failing?

**Comment by shwetajha25** [comment]
@wendigo 

I'm encountering an issue while trying to access the Web UI of the Trino cluster deployed on my Azure Kubernetes Cluster using path-based routing with the NGINX Ingress Controller. When I attempt to access the URL, I receive a "HTTP ERROR 404 Not Found" response.

**Ingress.yaml Configuration**

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "360"
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: trino287663-coordinator
  namespace: shweta-jha
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /trino287663
        pathType: Prefix
        backend:
          service:
            name: trino287663
            port:
              number: 8080
```

**Error Details**

When accessing the URL `http://ad439.accelerate.symphonyai.com/trino287663`, I receive the following error:

```
HTTP ERROR 404 Not Found
URI:    http://ad439.accelerate.symphonyai.com/trino287663
STATUS: 404
MESSAGE: Not Found
```

**Ingress-NGINX Logs on AKS**

```
20.244.33.247 - - [14/Aug/2024:07:36:26 +0000] "GET /trino287663 HTTP/1.1" 404 370 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36" 463 0.003 [shweta-jha-trino287663-8080] [] 10.108.0.247:8080 370 0.004 404
```

Any insights or suggestions on how to resolve this would be greatly appreciated.

**Comment by wendigo** [comment]
Is Nginx configured to send X-Forwarded-Prefix header and Trino configured to process these headers?

**Comment by shwetajha25** [comment]
@wendigo  

Yes, I have configured both NGINX and Trino to handle the `X-Forwarded-Prefix` header properly. Below are the details of the configurations:

### Trino Configuration:
I have added the necessary property in Trino's `config.properties` file to ensure that Trino processes forwarded headers correctly. This property enables Trino to understand and trust the `X-Forwarded-*` headers sent by NGINX.

Here’s the property that was added:
```yaml
http-server.process-forwarded=true
```

You can see this property is included in the ConfigMap for the Trino coordinator:
```bash
kubectl get cm example-trino-cluster-trino-coordinator -n test -o yaml | grep -i http-server.process-forwarded=true
    http-server.process-forwarded=true
```

Here’s the full `config.properties` section in the ConfigMap:
```yaml
apiVersion: v1
data:
  config.properties: |
    http-server.process-forwarded=true
    coordinator=true
    node-scheduler.include-coordinator=false
    http-server.http.port=8080
    query.max-memory=4GB
    query.max-memory-per-node=1GB
    discovery.uri=http://localhost:8080
  exchange-manager.properties: |
    exchange-manager.name=filesystem
    exchange.base-directories=/tmp/trino-local-file-system-exchange-manager
  jvm.config: |
    -server
    -agentpath:/usr/lib/trino/bin/libjvmkill.so
    -Xmx8G
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
  log.properties: |
    io.trino=INFO
  node.properties: |
    node.environment=production
    node.data-dir=/data/trino
    plugin.dir=/usr/lib/trino/plugin
kind: ConfigMap
metadata:
  name: example-trino-cluster-trino-coordinator
  namespace: test
```

### NGINX Configuration:
On the NGINX side, I have also added the necessary configuration to send the `X-Forwarded-Prefix` header. Specifically, I used the `nginx.ingress.kubernetes.io/x-forwarded-prefix` annotation in the Ingress resource to forward the prefix `/trino`.

Here’s the Ingress configuration:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/x-forwarded-prefix: /trino
  name: example-trino-cluster-trino
  namespace: test
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: example-trino-cluster-trino
            port:
              number: 8080
        path: /trino/?(.*)
        pathType: Prefix
  tls:
  - secretName: trino287663-trino-tls-secret
```

Additionally, the following NGINX block handles the request routing and passes the necessary `X-Forwarded-*` headers, including the `X-Forwarded-Prefix`:
```nginx
location ~* "^/trino/?(.*)" {
	
	set $namespace      "test";
	set $ingress_name   "example-trino-cluster-trino";
	set $service_name   "example-trino-cluster-trino";
	set $service_port   "8080";
	set $location_path  "/trino/?(.*)";
	set $global_rate_limit_exceeding n;
	
	rewrite_by_lua_block {
		lua_ingress.rewrite({
			force_ssl_redirect = false,
			ssl_redirect = false,
			force_no_ssl_redirect = false,
			preserve_trailing_slash = false,
			use_port_in_redirects = false,
			global_throttle = { namespace = "", limit = 0, window_size = 0, key = { }, ignored_cidrs = { } },
		})
		balancer.rewrite()
		plugins.run()
	}
	
	# be careful with `access_by_lua_block` and `satisfy any` directives as satisfy any
	# will always succeed when there's `access_by_lua_block` that does not have any lua code doing `ngx.exit(ngx.DECLINED)`
	# other authentication method such as basic auth or external auth useless - all requests will be allowed.
	#access_by_lua_block {
	#}
	
	header_filter_by_lua_block {
		lua_ingress.header()
		plugins.run()
	}
	
	body_filter_by_lua_block {
		plugins.run()
	}
	
	log_by_lua_block {
		balancer.log()
		
		plugins.run()
	}
	
	port_in_redirect off;
	
	set $balancer_ewma_score -1;
	set $proxy_upstream_name "test-example-trino-cluster-trino-8080";
	set $proxy_host          $proxy_upstream_name;
	set $pass_access_scheme  $scheme;
	
	set $pass_server_port    $server_port;
	
	set $best_http_host      $http_host;
	set $pass_port           $pass_server_port;
	
	set $proxy_alternative_upstream_name "";
	
	client_max_body_size                    1m;
	
	proxy_set_header Host                   $best_http_host;
	
	# Pass the extracted client certificate to the backend
	
	# Allow websocket connections
	proxy_set_header                        Upgrade           $http_upgrade;
	
	proxy_set_header                        Connection        $connection_upgrade;
	
	proxy_set_header X-Request-ID           $req_id;
	proxy_set_header X-Real-IP              $remote_addr;
	
	proxy_set_header X-Forwarded-For        $remote_addr;
	
	proxy_set_header X-Forwarded-Host       $best_http_host;
	proxy_set_header X-Forwarded-Port       $pass_port;
	proxy_set_header X-Forwarded-Proto      $pass_access_scheme;
	proxy_set_header X-Forwarded-Scheme     $pass_access_scheme;
	
	proxy_set_header X-Scheme               $pass_access_scheme;
	
	# Pass the original X-Forwarded-For
	proxy_set_header X-Original-Forwarded-For $http_x_forwarded_for;
	
	# mitigate HTTPoxy Vulnerability
	# https://www.nginx.com/blog/mitigating-the-httpoxy-vulnerability-with-nginx/
	proxy_set_header Proxy                  "";
	
	# Custom headers to proxied server
	
	proxy_connect_timeout                   5s;
	proxy_send_timeout                      60s;
	proxy_read_timeout                      60s;
	
	proxy_buffering                         off;
	proxy_buffer_size                       4k;
	proxy_buffers                           4 4k;
	
	proxy_max_temp_file_size                1024m;
	
	proxy_request_buffering                 on;
	proxy_http_version                      1.1;
	
	proxy_cookie_domain                     off;
	proxy_cookie_path                       off;
	
	# In case of errors try the next upstream server before returning an error
	proxy_next_upstream                     error timeout;
	proxy_next_upstream_timeout             0;
	proxy_next_upstream_tries               3;
	
	# Custom Response Headers
	
	rewrite "(?i)/trino/?(.*)" /$1 break;
	proxy_set_header X-Forwarded-Prefix "/trino";
	proxy_pass http://upstream_balancer;
	
	proxy_redirect                          off;
	
}
```

### Current Behavior:
Now, when I try accessing `http://example.com/trino`, it redirects to `http://example.com/%2Ftrino/ui/login.html`, which shows the authentication page. However, after entering the credentials, it redirects to `http://example.com/ui/login` and returns a `404 Not Found` error.

I suspect this is related to how the `X-Forwarded-Prefix` header is being processed during the login redirects, and I am currently investigating the issue further.

Here are the relevant NGINX logs from when I hit the URL:
```plaintext
20.244.33.247 - - [03/Sep/2024:17:23:25 +0000] "GET /%2Ftrino/ui/assets/favicon.ico HTTP/1.1" 200 15441 "http://example.com/%2Ftrino/ui/login.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" 417 0.001 [test-example-trino-cluster-trino-8080] [] 10.109.0.216:8080 15419 0.001 200 f46a4f4fd93a9c3b14ec2ac4980b3187

20.244.33.247 - - [03/Sep/2024:17:23:35 +0000] "GET /trino HTTP/1.1" 303 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" 491 0.002 [test-example-trino-cluster-trino-8080] [] 10.109.0.216:8080 0 0.001 303 938a5d165344a12ddbf7339819ae794f

20.244.33.247 - - [03/Sep/2024:17:23:36 +0000] "GET /%2Ftrino/ui/ HTTP/1.1" 303 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" 498 0.001 [test-example-trino-cluster-trino-8080] [] 10.109.0.216:8080 0 0.001 303 e67ff0c04565159dea82d6b8a2d1c34f

20.244.33.247 - - [03/Sep/2024:17:23:36 +0000] "GET /%2Ftrino/ui/login.html HTTP/1.1" 200 1157 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" 508 0.002 [test-example-trino-cluster-trino-8080] [] 10.109.0.216:8080 1157 0.002 200 b74e22b36e37bbd877d5cf0a3a29282f

20.244.33.247 - - [03/Sep/2024:17:23:36 +0000] "GET /%2Ftrino/ui/vendor/bootstrap/css/bootstrap.css HTTP/1.1" 200 21273 "http://example.com/%2Ftrino/ui/login.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" 439 0.006 [test-example-trino-cluster-trino-8080] [] 10.109.0.216:8080 21235 0.007 200 6f0e836a487644a611303199b4fe5c57

```

Could you please assist with resolving this? Any guidance on how to properly configure NGINX for this setup would be greatly appreciated.
