### ISSUE TITLE
Use consistent labels across repositories

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#24472]
The Trino Go client and Trino Helm chart repositories have adopted a consistent set of labels to classify pull requests and changes for automated release notes generation on GitHub.

It would be useful to have consistency across all our repositories with these labels and eventually start using them in releases in other projects.

Immediate candidates where we can see benefits are the trino python client and the trino csharp client. 

Even for other repositories it would be good to get into a habit of labelling PRs in a consistent manner and then we can potentially use this for release generation or even just for links to that use the labels in filters and maybe existing milestones we use in repositories like trino and trino-gateway.

The configuration in the YAML file from the go client 

https://github.com/trinodb/trino-go-client/blob/master/.github/release.yml

Shows the current labels:

```
changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - enhancement
    - title: Bug fixes
      labels:
        - bug
    - title: Other changes
      labels:
        - "*"
```

Next step would be to discuss these labels and potentially agree to them as a standard set. We would also add that info to the contributor and maintainer docs.

Ideally we could define the labels on the org level but maybe we have to do that and roll it out per repository.

Also note that this setup with labels should also work with jreleaser (used for airlift release automation and potentially going to be used for others)
