### ISSUE TITLE
Configuring HTTPS Ingress with AWS LoadBalancer

### ISSUE THREAD

**Issue by santurini** [trinodb/trino#25233]
I have a working Trino deployment on kubernetes which I was able to reach up to now using HTTPS with password authentication by [securing Trino directly](https://trino.io/docs/current/security/tls.html#secure-trino-directly).

This is the `values.yaml` I used for the Helm deployment:
```YAML
image:
  tag: "470"

catalogs:
  mycatalog: |-
     .....

server:
  workers: 2
  config:
    authenticationType: PASSWORD

additionalConfigProperties:
  - http-server.https.keystore.path=/etc/trino/keystore/keystore.jks
  - http-server.https.keystore.key=thepassword
  - http-server.https.enabled=true
  - http-server.https.port=8443
  - http-server.process-forwarded=true
  - internal-communication.shared-secret=theactualsecret
auth:
  passwordAuthSecret: trino-password-authentication

env:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: trino-aws-credentials
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: trino-aws-credentials
        key: AWS_SECRET_ACCESS_KEY
  - name: AWS_REGION
    value: eu-central-1

secretMounts:
  - name: trino-keystore
    secretName: trino-keystore
    path: /etc/trino/keystore

service:
  type: ClusterIP

ingress:
  enabled: true
  className: contour
  tls:
    - hosts:
      - trino.mydomain.com
      secretName: mydomain.com
  hosts:
    - host: trino.mydomain.com
      paths:
        - path: /
          pathType: Prefix
```

Now, when I try to reach Trino over HTTPS with a Load Balancer upfront, even if I already have the `http-server.process-forwarded=true`, I get this error:

> 400 Bad Request: The plain HTTP request was sent to HTTPS port

In the Load Balancer I handle the TLS certification and then I communicate with the cluster over port 80.
How can I keep reaching the Trino UI at https://trino.mydomain.com using password authentication switching to a Load Balancer?

**Comment by santurini** [comment]
I tried to do some tests, for instance removing password authentication and https related properties, and removing TLS from the ingress definition:
```YAML
additionalConfigProperties:
  - http-server.process-forwarded=true
  - internal-communication.shared-secret=theactualsecret

ingress:
  enabled: true
  className: contour
  hosts:
    - host: trino.mydomain.com
      paths:
        - path: /
          pathType: Prefix
```

When I want to reach `trino.mydomain.com` I am redirected to this URL `https://trino.mydomain.com:443/ui/login.html`.
that yields:

> 400 Bad Request The plain HTTP request was sent to HTTPS port

Of course if I edit the URL to HTTP `http://trino.mydomain.com /ui/login.html` everything works fine, but I everything I wanted is no more available.

That is having password authentication and reaching the service over HTTPS with a load balancer in front.
Previously without using the Load Balancer I had both, and I had a route in AWS Route53 that mapped `trino.mydomain.com` to the master IP of the cluster.

Now the difference is that the `trino.mydomain.com` is mapped to the CNAME of the Load Balancer and in the Load Balancer I have a rule that for HTTPS:443 if the Host Header is *.mydomain.com it redirects to the target group that is defined like this:

> ${master_ip}:80

I don't get what I am doing wrong, I just want to handle SSL certification by keeping the same hostname for the service and the password authentication.

**Comment by dain** [comment]
I searched the Trino codebase and this doesn't look like an error message from us.  Then I searched google and it looks like that is an Nginx message.

**Comment by santurini** [comment]
The error is a networking error but it depends from the fact that the ALB is doing the certificate verification and forwarding an HTTP request to Trino. I want to know how to setup the ingress if I'm using the ALB as if I follow the trino documentation it does not work

**Comment by santurini** [comment]
@lozbrown trino requires https communication to enable password authentication, ideally I would prefer to terminate the HTTPS communication in the ALB as I do for all the services in the kubernetes cluster and then redirect the HTTP request to the cluster's masters but it seems like Trino forces port 443 on the http request

**Comment by santurini** [comment]
@lozbrown And what is the key difference with my configuration? Only this?
`http-server.https.enabled=false`

**Comment by lozbrown** [comment]
> @lozbrown And what is the key difference with my configuration? Only this?
> `http-server.https.enabled=false`

Yep, I think so

**Comment by santurini** [comment]
@lozbrown Have you set also these keys or can I remove them?
`http-server.https.keystore.path`
`http-server.https.keystore.key`

**Comment by lozbrown** [comment]
> [@lozbrown](https://github.com/lozbrown) Have you set also these keys or can I remove them? `http-server.https.keystore.path` `http-server.https.keystore.key`

i think you can remove

**Comment by santurini** [comment]
I tried using this configuration:
```YAML
image:
  tag: "470"

...
    
server:
  config:
    authenticationType: PASSWORD

additionalConfigProperties:
  - http-server.process-forwarded=true
  - internal-communication.shared-secret=...
auth:
  passwordAuthSecret: trino-password-authentication

service:
  type: ClusterIP

ingress:
  enabled: true
  className: contour
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    - hosts:
      - trino.domain.com
      secretName: domain.com
  hosts:
    - host: trino.domain.com
      paths:
        - path: /
          pathType: Prefix
```

This is my ALB setup:
![Image](https://github.com/user-attachments/assets/9333b1f6-0e41-4685-8979-ed81c7e4b6ca)
![Image](https://github.com/user-attachments/assets/ea90e159-4dab-477c-bb2d-848921c0fee1)

The target group is `{k8s-master-IP}:80`.

If I navigate to https://trino.domain.com I get this error:
![Image](https://github.com/user-attachments/assets/f53f885d-2e67-43ac-9b63-131cf19c0744)

Is it trino or the ALB the problem, I don't get it.
