### ISSUE TITLE
Best settings to prevent out-of-memory errors

### ISSUE THREAD

**Issue by santurini** [trinodb/trino#25341]
Hello,
I have deployed trino in my kubernetes cluster using the helm chart. Everything works fine until I run a series of queries sequentially where some of them systematically return `INTERNAL ERROR — REMOTE TASK ERROR` or timeout.

If I rerun those failing queries in a second moment everything works fine.
From the log it seems that a worker node is failing, thus I wanted to know how should I change my helm deployment to prevent that without sacrificing speed, this is my actual deployment:
```YAML
catalogs:
  golden: |-
    connector.name=hive
    ...
    retry-policy=QUERY
    query-retry-attempts=3
    retry-initial-delay=1m
    retry-max-delay=2m
    retry-delay-scale-factor=1

server:
  workers: 4

worker:
  jvm:
    maxHeapSize: "8G"
  config:
    memory:
      heapHeadroomPerNode: "4GB"
    query:
      maxMemoryPerNode: "4GB"
  resources:
    requests:
      cpu: "2"
      memory: "12Gi"
    limits:
      cpu: "2"
      memory: "16Gi"

coordinator:
  jvm:
    maxHeapSize: "8G"
  config:
    memory:
      heapHeadroomPerNode: "4GB"
    query:
      maxMemoryPerNode: "4GB"
```
