### ISSUE TITLE
OpenMetrics Endpoint showing duplicate metrics

### ISSUE THREAD

**Issue by metalshanked** [trinodb/trino#25417]
I am trying to scrape the metrics from the default openmetrics endpoint `/metrics` from only the ingress (which points to the coordinator)
I see metrics showing up for both the coordinator and workers.
However, they seem to be duplicated as shown in the screenshot below

Set the OpenMetrics endpoint with default options 
`openmetrics.jmx-object-names=:*` 

Using a ServiceMonitor object like below 
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: kube-prometheus
  name: trino-cluster-coordinator-and-worker
  namespace: trino
spec:
  endpoints:
    - basicAuth:
        password:
          key: password
          name: trino-basic-auth
        username:
          key: username
          name: trino-basic-auth
      interval: 30s
      port: http
      relabelings:
        - action: replace
          regex: (.*)
          replacement: my-trino-coordinator-ingress:443
          sourceLabels:
            - __address__
          targetLabel: __address__
      scheme: https
      tlsConfig:
        insecureSkipVerify: false
  namespaceSelector:
    matchNames:
      - trino
  selector: {}
```

Metric values are duplicated. 
Example: I ran one query but the metrics show "2" for all three endpoints

![Image](https://github.com/user-attachments/assets/6c4c8c70-1889-4042-b48a-6897e110da91)
