### ISSUE TITLE
[Improvement] Use real dataset location in OpenLineage integration

### ISSUE THREAD

**Issue by dolfinus** [trinodb/trino#25555]
Currently OpenLineage returns dataset with fields like:
```
namespace: trino://localhost:8080
name: mycatalog.myschema.mytable
```

But Trino catalog is just alias for real dataset location. For example, if this is a table in Postgres, dataset should point to its real location:
```
namespace: postgres://localhost:5432
name: mydb.myschema.mytable
```

Or by linking catalog with real database location using `SYMLINK`:
```
namespace: trino://localhost:8080
name: mycatalog.myschema.mytable
symlinks:
  - type: LOCATION
    namespace: postgres://localhost:5432
    name: mydb.myschema.mytable
```

**Comment by wendigo** [comment]
This is not possible to implement currently as the engine doesn't know the database connector is connecting to (this is part of the JDBC url that is a configuration detail of the catalog).

**Comment by dolfinus** [comment]
As I see, [CatalogStore.getCatalogs](https://javadoc.io/static/io.trino/trino-spi/474/trino.spi/io/trino/spi/catalog/CatalogStore.html#getCatalogs()) allows to iterate over all catalogs, find specific one by name, and fetch all properties, including JDBC URL. Although, without `connectorName` attribute it will be hard to distinguish between jdbc catalog and other types. And also this is O(n) operation which can be replaced with O(1) with proper API.

Without information about real dataset location, companies using multiple tools to access the same table (Trino, Spark, Airflow operators and so on) will see one lineage tree for Trino:
```
Run1:
  namespace: trino://localhost:8080
  name: queryId
  inputs:
    - Dataset1:
        namespace: trino://localhost:8080
        name: pgcatalog.pgschema.pgtable
    - Dataset2:
        namespace: trino://localhost:8080
        name: mysqlcatalog.mysqlschema.mysqltable
```
and completely different tree for all other tools:
```
Run1:
  namespace: spark://localhost
  name: my-spark-session
  inputs:
    - Dataset1:
        namespace: postgres://localhost:5432
        name: pgdb.pgschema.pgtable
    - Dataset2:
        namespace: mysql://localhost:3306
        name: mysqldb.mysqlschema.mysqltable
Run2:
  namespace: airflow://localhost:8081
  name: somedag.sometask
  inputs:
    - Dataset2:
        namespace: mysql://localhost:3306
        name: mysqldb.mysqlschema.mysqltable
Run3:
  namespace: flink://localhost:8088
  name: somejob
  inputs:
    - Dataset1:
        namespace: postgres://localhost:5432
        name: pgdb.pgschema.pgtable
```

This is not very useful for end users.
