### ISSUE TITLE
Concurrency error when optimizing iceberg tables

### ISSUE THREAD

**Issue by santurini** [trinodb/trino#25584]
I am running a change data capture to stream tables changes from mysql to iceberg and read those tables using trino iceberg connector with nessie catalog.

I am trying to run an optimize on the tables but for larger tables it takes more than the commit interval of the change data capture therefore I keep getting this error:
```
io.trino.spi.TrinoException: Failed to commit the transaction during optimize: Cannot commit, found new delete for replaced data file: GenericDataFile{content=data, file_path=s3a://warehouse/translated/languages_6b7919b8-a86e-4e80-b803-b1f685e4d91e/data/APPROVED_DATE_year=2019/00001-1744698616017-f4ff3097-5050-4e09-a05e-25a07ad8c7fd-00005.parquet, file_format=PARQUET, spec_id=0, partition=PartitionData{APPROVED_DATE_year=49}, record_count=4, file_size_in_bytes=12479, column_sizes=null, value_counts=null, null_value_counts=null, nan_value_counts=null, lower_bounds=null, upper_bounds=null, key_metadata=null, split_offsets=[4], equality_ids=null, sort_order_id=0, data_sequence_number=347, file_sequence_number=347}
```

Is there something I can do from the trino side to prevent this error?
I wanted to avoid increasing the commit time because I would like to reflect the table changes almost in real time.

**Comment by raunaqmorarka** [comment]
Is the CDC capture process writing position deletes or equality deletes ? My guess is that writing equality deletes could avoid this problem as position deletes reference position numbers in the replaced data file while equality deletes do not.
You could also use partition or `$file_modified_time` or `$path` filters on the OPTIMIZE command to target smaller portions of the table and reduce the chances of conflict with the CDC capture process.

**Comment by santurini** [comment]
I am using [Apache Iceberg Kafka Connector](https://iceberg.apache.org/docs/nightly/kafka-connect/), I tried searching on the internet and it seems that the default is Copy-on-Write but I haven't found whether it uses equality or position deletes, I know that using format-version v3 would deprecate position deletes and maybe give it a try.

While I already tried as you suggested to add constraints to the optimize in hours and days but getting the same problem:
```
ALTER TABLE "jobs" EXECUTE optimize WHERE "$file_modified_time" < current_timestamp - interval '3' HOUR;
ALTER TABLE "jobs" EXECUTE optimize WHERE "$file_modified_time" < current_timestamp - interval '1' DAY;
```

The optimize takes around 40 minutes so various commits can occurr in the meantime.

**Comment by raunaqmorarka** [comment]
Can you try setting `iceberg.tables.upsert-mode-enabled=true` for the ingest ? The default seems to be position deletes and setting that should result in equality deletes.
Also, V3 spec is not removing position deletes, it just changed the way they are stored for better efficiency.

**Comment by santurini** [comment]
I already have it, this is the template I am using:
```
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: sink-{{DATABASE}}-{{CONNECTOR_NAME}}
  namespace: confluent
spec:
  class: io.tabular.iceberg.connect.IcebergSinkConnector
  connectClusterRef:
    name: connect
  taskMax: 1
  configs:
    topics: trino.{{DATABASE}}.{{TABLE}}
    iceberg.tables: {{DATABASE}}.{{TABLE}}
    iceberg.table.{{DATABASE}}.{{TABLE}}.id-columns: {{TABLE_PRIMARY_KEY}}
    iceberg.table.{{DATABASE}}.{{TABLE}}.partition-by: {{TABLE_PARTITION_KEY}}
    iceberg.tables.upsert-mode-enabled: "true"
    iceberg.tables.auto-create-enabled: "true"
    iceberg.tables.schema-case-insensitive: "true"
    iceberg.tables.evolve-schema-enabled: "true"
    iceberg.catalog: {{DATABASE}}
    iceberg.catalog.catalog-impl: org.apache.iceberg.nessie.NessieCatalog
    iceberg.catalog.warehouse: s3a://warehouse
    iceberg.catalog.ref: main
    iceberg.catalog.uri: http://nessie.nessie.svc.cluster.local:19120/api/v2
    iceberg.catalog.io-impl: org.apache.iceberg.aws.s3.S3FileIO
    iceberg.catalog.s3.endpoint: https://minio.mydomain.com
    iceberg.catalog.s3.path-style-access: "true"
    iceberg.control.commit.interval-ms: "900000"
    iceberg.s3.endpoint: https://minio.mydomain.com
    iceberg.s3.path-style-access: "true"
    transforms: {{TRANSFORMS}}
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
```
