### ISSUE TITLE
catalog.management=dynamic is invalid in k8s environment

### ISSUE THREAD

**Issue by A-little-bit-of-data** [trinodb/trino#25651]
In the k8s environment, version 474 is deployed and catalog.management=dynamic is set. When I use the following catalog statement:
 ```
CREATE CATALOG s3sit USING hive
WITH (
"hive.metastore.uri"='thrift://hive-metastore:9083',
"hive.metastore.username"='trino',
"hive.metastore.thrift.client.connect-timeout"='3m',
"hive.metastore.thrift.client.read-timeout"='3m',
"fs.native-s3.enabled"='true',
"s3.endpoint"='http://test:8060,
"s3.region"='xxx',
"s3.path-style-access"='true',
"s3.aws-access-key"='xxxxx',
"s3.aws-secret-key"='xxxxx'
);
```

The error is as follows: 
```
io.trino.connector.FileCatalogStore Could not store catalog properties for s3sit

2025-04-23T13:43:28.591594058+08:00 java.io.FileNotFoundException: /data/trino/etc/catalog/s3sit.properties.tmp (Read-only file system)
```

See
```
 - name: catalog-volume
configMap:
name: trino-catalog
defaultMode: 420

- name: catalog-volume
              mountPath: /etc/trino/catalog
``` 
is mounted through configmap, but configmap is read-only and cannot be modified. According to the document, `catalog.config-dir` can be set, but `catalog.management` needs to be set to `static`  

Is it possible to only use memory?
