### ISSUE TITLE
Trino cannot properly work with REST catalog prefix option

### ISSUE THREAD

**Issue by tnhgiang** [trinodb/trino#25760]
When I don't specify value for `iceberg.rest-catalog.prefix` in `catalog.properties`, everything is fine. Otherwise, trino crashes

Here is my configuration for the `gold` catalog:
```properties
connector.name=iceberg
iceberg.file-format=parquet

iceberg.catalog.type=rest
iceberg.rest-catalog.uri=${ENV:CATALOG_URI}
# Avoid multiple catalogs sharing the same Iceberg metadata (tables)
iceberg.rest-catalog.warehouse=${ENV:WAREHOUSE}/gold
iceberg.rest-catalog.prefix=gold

fs.native-s3.enabled=true
s3.endpoint=${ENV:S3_AWS_ENDPOINT}
s3.region=${ENV:S3_AWS_REGION}
s3.aws-access-key=${ENV:S3_AWS_ACCESS_KEY}
s3.aws-secret-key=${ENV:S3_AWS_SECRET_KEY}
s3.path-style-access=true

```

Trino cannot `show schemas, create schemas`

**Comment by ebyhr** [comment]
Please share the error message and full stacktrace.

**Comment by tnhgiang** [comment]
@ebyhr To reproduce the error, I'll use 2 different catalogs

## Gold
```
connector.name=iceberg
iceberg.file-format=parquet

iceberg.catalog.type=rest
iceberg.rest-catalog.uri=${ENV:CATALOG_URI}
# Avoid multiple catalogs sharing the same Iceberg metadata (tables)
iceberg.rest-catalog.warehouse=${ENV:WAREHOUSE}/gold
iceberg.rest-catalog.prefix=gold

fs.native-s3.enabled=true
s3.endpoint=${ENV:S3_AWS_ENDPOINT}
s3.region=${ENV:S3_AWS_REGION}
s3.aws-access-key=${ENV:S3_AWS_ACCESS_KEY}
s3.aws-secret-key=${ENV:S3_AWS_SECRET_KEY}
s3.path-style-access=true
```

## Silver

**I do not specify `iceberg.rest-catalog.prefix` in silver catalog**
```
connector.name=iceberg
iceberg.file-format=parquet

iceberg.catalog.type=rest
iceberg.rest-catalog.uri=${ENV:CATALOG_URI}
iceberg.rest-catalog.warehouse=${ENV:WAREHOUSE}/silver

fs.native-s3.enabled=true
s3.endpoint=${ENV:S3_AWS_ENDPOINT}
s3.region=${ENV:S3_AWS_REGION}
s3.aws-access-key=${ENV:S3_AWS_ACCESS_KEY}
s3.aws-secret-key=${ENV:S3_AWS_SECRET_KEY}
s3.path-style-access=true

```

## Show available catalogs

```
trino> show catalogs;
 Catalog 
---------
 gold    
 silver  
 system  
(3 rows)

Query 20250510_154852_00000_9v4qt, FINISHED, 1 node
Splits: 11 total, 11 done (100.00%)
0.90 [0 rows, 0B] [0 rows/s, 0B/s]
```
Everything works fine

## Show schemas in each catalogs
```
trino> show schemas in gold;

Query 20250510_155038_00001_9v4qt, FAILED, 1 node
Splits: 11 total, 10 done (90.91%)
0.38 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20250510_155038_00001_9v4qt failed: Error listing schemas for catalog gold: Failed to list namespaces

trino> show schemas in silver;
       Schema       
--------------------
 information_schema 
(1 row)

Query 20250510_155051_00002_9v4qt, FINISHED, 1 node
Splits: 11 total, 11 done (100.00%)
0.26 [1 rows, 23B] [3 rows/s, 90B/s]
```

**Cannot list schemas in the gold catalog**

## Create schema in each catalogs;
```
trino> create schema gold.test;
Query 20250510_155642_00003_9v4qt failed: Failed to check namespace 'test'

trino> create schema silver.test;
CREATE SCHEMA
```
**Cannot create a new schema in the gold catalog**

**Comment by findinpath** [comment]
Pls share the stacktrace in the original report as well.

**Comment by tnhgiang** [comment]
@findinpath Where can I find the stacktrace @findinpath. Is it the trino logger?

**Comment by ebyhr** [comment]
@tnhgiang You can find it with `--debug` CLI option or Web UI.

**Comment by tnhgiang** [comment]
I'm using REST catalog version 1.8.1. Here is my `compose file` to run `REST catalog`
```
  rest:
    image: apache/iceberg-rest-fixture:1.8.1
    hostname: ${REST_CATALOG_HOST}
    container_name: iceberg-rest
    ports:
      - ${REST_CATALOG_PORT}:${REST_CATALOG_PORT}
    environment:
      CATALOG_URI: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_CATALOG_DB}
      CATALOG_JDBC_USER: ${POSTGRES_USER}
      CATALOG_JDBC_PASSWORD: ${POSTGRES_PASSWORD}
      AWS_REGION: ${MINIO_REGION}
      CATALOG_WAREHOUSE: s3a://${MINIO_WAREHOUSE_BUCKET}/
      CATALOG_IO__IMPL: org.apache.iceberg.aws.s3.S3FileIO
      CATALOG_S3_ENDPOINT: ${MINIO_ENDPOINT}
      CATALOG_S3_ACCESS__KEY__ID: ${MINIO_ROOT_USER}
      CATALOG_S3_SECRET__ACCESS__KEY: ${MINIO_ROOT_PASSWORD}
      CATALOG_S3_PATH__STYLE__ACCESS: true
    volumes:
      - ../src/lakehouse/postgresql/driver/postgresql-42.7.5.jar:/usr/lib/iceberg-rest/postgresql-42.7.5.jar
    command: java -cp /usr/lib/iceberg-rest/*:iceberg-rest-adapter.jar org.apache.iceberg.rest.RESTCatalogServer
    depends_on:
      postgresql:
        condition: service_healthy
      minio:
        condition: service_healthy

```
