### ISSUE TITLE
Trino UI and JMX incorrectly report heap memory size (regression from 450 to 47X)

### ISSUE THREAD

**Issue by saadsb20** [trinodb/trino#26052]
## Bug Description
Trino 476 UI and JMX metrics are incorrectly reporting heap memory size, showing 50.3GB instead of the actual configured 15G. The JVM itself is correctly configured with the right heap size, but Trino's memory reporting mechanism is broken. This appears to be a regression as the same configuration reports correctly in Trino 450.

## Environment
- **Trino Version**: 476 (regression), works correctly in 450
- **Deployment Method**: Helm Chart (trinodb/trino)
- **Kubernetes Version**: 1.31.2

## Configuration
**Helm values.yml (relevant sections):**
```yaml
image:
  tag: "476"

coordinator:
  jvm:
    maxHeapSize: "15G"
    gcMethod:
      type: "UseG1GC"
      g1:
        heapRegionSize: "32M"

worker:
  jvm:
    maxHeapSize: "15G"
    gcMethod:
      type: "UseG1GC"
      g1:
        heapRegionSize: "32M"

# No Kubernetes resource limits set
coordinator:
  resources: {}
worker:
  resources: {}
```

## Expected Behavior
- Trino UI should show **~15GB** heap memory (matching JVM configuration)
- JMX metrics should report **~15GB** heap memory
- Reported heap size should match actual JVM heap allocation

## Actual Behavior
- **Trino UI shows 50.3GB** heap memory (incorrect)
- **JMX metrics report 50.3GB** heap memory (incorrect)
- **JVM is correctly configured** with 15.7G heap size (verified with `java -XshowSettings:all`)

## Evidence
**JVM Configuration (CORRECT):**
```bash
[trino@trino-worker-766fb8445-7j4xk /]$ java -XshowSettings:all
VM settings:
    Max. Heap Size (Estimated): 15.70G
    Using VM: OpenJDK 64-Bit Server VM
```

**Trino UI Reporting (INCORRECT):** Shows 50.3GB heap memory

## Steps to Reproduce
1. Deploy Trino 476 using Helm chart with `jvm.maxHeapSize: "15G"` 
2. Do not set Kubernetes resource limits (`resources: {}`)
3. Check Trino UI → Worker Status → Heap Memory
4. Observe that heap memory shows a different value instead of 15GB.

## Regression Information
- **Working Version**: Trino 450 - correctly shows 15GB heap memory with identical configuration
- **Broken Version**: Trino 476 and back till 470 - shows 50.3GB heap memory
- **Configuration**: Identical Helm values.yml used for both versions

## Investigation
- **JVM is correctly configured**: `java -XshowSettings:all` shows `Max. Heap Size (Estimated): 15.70G`
- **Trino reporting is wrong**: UI and JMX show 50.3GB instead of actual 15.7G
- Issue appears to be with Trino's memory detection/reporting mechanism, not JVM configuration
- Problem occurs even when JVM heap is correctly set

## Possible Root Cause
Changes to Trino's memory reporting logic between versions 450-476 may be incorrectly detecting or calculating heap memory size for display in UI and JMX metrics, while the actual JVM heap allocation remains correct.

## Additional Context
This regression affects monitoring and capacity planning in production deployments where accurate memory reporting is critical. While the actual JVM memory allocation is correct, the incorrect reporting in UI and JMX makes it impossible to properly monitor memory usage and could lead to incorrect scaling decisions.

## Possible Root Cause
Changes to memory auto-detection logic between versions 450-476 may be prioritizing system memory detection over explicit `maxHeapSize` configuration when no container limits are present.
